### PR TITLE
Raml1.0 - Add support for multiple examples

### PR DESCRIPTION
**Pull request by jerrobertson**
Basic multiple example support. Will also examine if each example contains a `displayName` and/or `description` field. Example RAML (and resulting HTML) updated.

Also displays examples parsed as JSON if the media type is `application/json` (This could possibly be adjusted so that it is controlled by a CLI switch).

### CODE REVIEW

**Comment by sichvoge** [comment]
@jeremyrobertson can you add a picture and maybe host a simple HTML page so I can have a look at this fast w/o building it :) BTW, can you merge the current branch version into your PR

**Comment by sichvoge** [comment]
You might have to do some changes based on PR #239

**Comment by sichvoge** [comment]
OH I think it actually support multiple examples already ;)

**Comment by jerrobertson** [comment]
Yeah, it looks like that may supersede what I did. I'll check it out.

**Comment by jerrobertson** [comment]
it's really good (much better than what I had put together), but we're using the displayName and description on the examples as well. I think we can close this one out and I may post another PR that handles those fields.

**Pull request closed without merging**
