### PR TITLE
Improve multiple security schemes handling

### PR DESCRIPTION
**Pull request by DAICHl**
If there is more than one security scheme,
the generated html doesn't describe all of
them properly.

### CODE REVIEW

**Comment by DAICHl** [comment]
I just noticed that this issue has already been reported at https://github.com/raml2html/raml2html/issues/214 by @gyszalai.

Anyway, I appreciate if you could fix the issue on master branch.

**Comment by sichvoge** [comment]
I need to spend some time on that. Can you host a version that I can have a look at this? Maybe also adding some images help a lot :)

**Comment by sichvoge** [comment]
BTW, can you change master to develop pls

**Comment by DAICHl** [comment]
OK, I will.

**Comment by kevinrenskers** [comment]
Please submit PR's to the develop branch, thanks.

**Pull request closed without merging**
