### PR TITLE
upgrade nunjucks and fix template

### PR DESCRIPTION
**Pull request by chulkilee**
- old version of nunjucks depends on old version of fsevents via
  chokidar, which does not work on node 6.x. See
  https://github.com/strongloop/fsevents/pull/128

- nunjucks-markdown expect blocks at the same level with {% markdown %}
  tag. So fix the template.

### CODE REVIEW

**Comment by milesoldenburg** [comment]
Thanks, @chulkilee, this solves my problem and I believe will fix #229 and #220. Tested with node v6.2.0 on OSX 10.10.5.

**Comment by milesoldenburg** [comment]
The contribution guidelines specify to set target to the `develop` branch, which might help the process.

**Comment by sichvoge** [comment]
Agree to @milesoldenburg. @chulkilee please set the target to develop

**Comment by chulkilee** [comment]
Opened #231 to the `develop` branch

**Pull request closed without merging**
