### PR TITLE
raml2html as a Docker image

### PR DESCRIPTION
**Pull request by mstrzele**
I've created [an organization on Docker Hub](https://hub.docker.com/u/raml2html/) and pushed the first version of [raml2html 3.0.0 image](https://hub.docker.com/r/raml2html/raml2html/tags/). If you're interested in merging it, I can transfer the ownership to you and describe how to build images when the new version is released.

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Could you simply link to the docker thing instead of adding the usage documentation into this readme? Just like the grunt and gulp plugins in the readme: we mention them, link to them, but that's it. We don't want to be responsible for maintaining this usage example :)

**Comment by kevinrenskers** [comment]
So by the same logic I also don't think we should include a Dockerfile in this repo. It's not directly related to raml2html the tool, and should be maintained in your own repo with examples etc. Thanks, hope you understand! :)

**Comment by mstrzele** [comment]
The good practise is to store the `Dockerfile` as close to the source code as possible. This allows to build Docker image each time the source code is released. Of course if you don't want to follow this, you can close this PR. I will create a separate repository for this. 😄

**Comment by kevinrenskers** [comment]
Well I don't use Docker and would have no clue how to maintain that file (nor a wish to do so). I'm also scared we end up with 10 tool config files, considering how fast the IT world, especially in JavaScript, moves. 

Let's see what the other maintainers say.

**Comment by fesor** [comment]
@mstrzele Cool!

If you will ended up with separate repository, you could just use webhooks to sync tags with this repo. Since `Dockerfile` for this project is very simple, i don't think that there should be any problems with that.

**Comment by kevinrenskers** [comment]
Pinging @mikestowe and @sichvoge for their input.

**Comment by kevinrenskers** [comment]
Sorry, closing this one. If you end up putting the Dockerfile in a separate repo, please feel free to make another PR that simply links to it, just like the Grunt and Gulp plugins do.

**Pull request closed without merging**
