### PR TITLE
Change the way security schemes are rendered to a more consistent way.

### PR DESCRIPTION
**Pull request by psychoo118**
Introduces a new render helper function: getSecuritySchemeName and moves the logic of renderSecuredBy to the templates.

### CODE REVIEW

**Comment by sichvoge** [comment]
That's nice. So basically you separated the functional part from rendering. If there is any possibility, I'd add some test even if that function is very small.

**Comment by psychoo118** [comment]
Yes as you say. How am I supposed to test this?

**Comment by nickwb** [comment]
These are all good changes, @psychoo118, but I think we can refactor a bit to make the template a lot neater.

I think there is opportunity to take some of the logic away from the template, and push it down in to **raml2obj**. The extra advantage is there is existing testing infrastructure in raml2obj which we can use to write some new tests for this.

Here's my suggestion:
**raml2obj** should guarantee that:
1. The `displayName` property of a security scheme always exists. We should set it - if it was not already provided - to be the same as the scheme name/key. (We do something similar now with examples: [See here](https://github.com/raml2html/raml2obj/blob/master/consistency-helpers.js#L44))
2. `securedBy` is either an array or `undefined`
3. `securedBy` should not be an empty array, or an array containing only `null` elements. In these cases `securedBy` should be `undefined`. There is an existing test for this, `secured-by-null`.
3. each element of a `securedBy` array is always an object, containing a `schemeName` string property and optional property for `scopes`. This won't be backwards compatible for people running custom templates, but I think that's fine.

An example object for `securedBy` could be:
```js
{
  securedBy: [
    {
      schemeName: 'oauth_2_0',
      scopes: [ 'ADMINISTRATOR' ]
    }
  ]
}
```


Happy to hear your thoughts/opinions.

**Comment by psychoo118** [comment]
I agree with you. I think this would be a much better solution. I also thought about this but I ended up with that it is somehow a change that could break compatibility with other packages than raml2html and tried to solve the issue without touching raml2obj. On the other hand I think how securitySchemes and securedBy are treated should be improved and we should figure out a standard format like the one you suggested.

**Comment by kevinrenskers** [comment]
I agree with everything Nick said: make stuff consistent and workable within raml2obj. It might break other packages or templates so probably best to release it as a major version update (5.0.0).

**Comment by psychoo118** [comment]
okay then the next question is who would like to implement Nick's idea? In the evening I can look into it if nobody have the time to do it :)

**Comment by nickwb** [comment]
I've pushed up a branch on to [raml2obj:security-scheme](https://github.com/raml2html/raml2obj/tree/security-scheme).

I've implemented the above, with perhaps a few subtle tweaks. Tests are still to come. Feel free to review. Or to write me some tests 😛

**Comment by psychoo118** [comment]
I made the tests for you and also adjusted other tests according to new output. :simple_smile:
psychoo118/raml2obj:security-scheme

**Comment by nickwb** [comment]
That's awesome Peter, thank you! I've pulled your commits up on to that raml2obj branch.

Sadly I do not have time to work on it further tonight, but a couple of notes:

1. I haven't looked too closely, but the linter seems to be unhappy with a couple of things, would be good if we could fix those up. (Run `npm run lint`).
2. Really happy with the test coverage you have, but would be good to get at least one test where the `scopes` property is supplied on the `securedBy` element.

Seems like it is quite close, so a release should not be too far off.

**Comment by psychoo118** [comment]
I knew I'd forget something.. the scopes :smile: I will extend the tests tonight. Oh and the linter errors will be fixed too.

**Comment by psychoo118** [comment]
Nevermind, I fixed now the issues mentioned above, check my repo.

**Comment by nickwb** [comment]
Great stuff. I've pulled your commits and landed that branch on develop 👍

**Comment by kevinrenskers** [comment]
@nickwb please don't commit to develop, do it via PR's instead. Thanks!

**Comment by kevinrenskers** [comment]
So I guess this PR can be closed, we can release raml2obj 5.0.0 soon, and then release a new raml2html that uses that with changed templates?

**Comment by psychoo118** [comment]
I think we can close this, I will make a PR in raml2html that will work with raml2obj 5.0.0

**Pull request closed without merging**
