### PR TITLE
Fix optional typed properties of items

### PR DESCRIPTION
**Pull request by psychoo118**
Fixes issue #297

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Thanks! Looks good, but I need to find the time to test the original bug report and the fix, unless @MichaelIT, @nickburns2006 or @nickwb want to jump in and help with that. 

If so: please test the bug report first, then test this PR with that same test file, and let me know if it all works so I can merge.

**Comment by psychoo118** [comment]
I tested it with the attachment of the original bug report before fix and after fix that's why I created the PR :)

**Comment by kevinrenskers** [comment]
I don't doubt that you did, but of course it needs to be verified and tested before merging and releasing any changes :)

**Comment by psychoo118** [comment]
of course :), sorry I'm new to contributing, still need to learn a lot :D

**Comment by kevinrenskers** [comment]
No problem, thanks for the PR's so far! Awesome that you're contributing.

**Comment by kevinrenskers** [comment]
BTW for future PR's, please choose the develop branch as the target, not master. Thanks!

**Comment by nickwb** [comment]
Hey guys. I was able to verify the bug - and I was able to verify the solution on your branch, @psychoo118.

That said - I don't think we need this PR. This bug can also be fixed by using the unreleased version of raml2obj on `raml2html/raml2obj:develop`. The outputs that I got using this branch and using the raml2obj:develop were binary identical. 

As a side note - for manipulating the parser output like this, I'd prefer to see changes to `consistency-helpers.js` in **raml2obj** rather than up here in the template.

Thanks for your contribution @psychoo118 - Sorry if I have undone some of your hard work.

**Comment by psychoo118** [comment]
No problem, I absolutely agree with you.
I just don't know how should I decide what is the source of issues like this one. Is there any spec defining how input of raml2html should look like? As I see raml2obj is a middleware between raml-js-parser-1 and raml2html to create consistent and useable input for raml2html and it is confusing for me to decide whether I should fix an issue in raml2obj or in raml-js parser-1.

**Comment by kevinrenskers** [comment]
If it's purely a rendering thing, then templates in raml2html can simply be changed. If you see that the data you're working with isn't handy or could be improved in some way, then it's better to fix the output in raml2obj instead of working with nasty data in raml2html.

**Comment by kevinrenskers** [comment]
Especially if it'll benefit other projects that depend on raml2obj. On the other hand, if it's a breaking change that's only handy for raml2html and not for anyone else, then perhaps it's better to fix it without upsetting other users of raml2obj.

**Comment by kevinrenskers** [comment]
@nickwb this PR is closed, but was the original problem (#297) fixed with raml2obj 4.1.0? Could you or @psychoo118 please check that bug report, see if it still needs work?

**Comment by psychoo118** [comment]
I can check it tomorrow. :)

**Pull request closed without merging**
