### PR TITLE
Expand $ref properties by using ramljsonexpander

### PR DESCRIPTION
**Pull request by nickveenhof**

### CODE REVIEW

**Comment by nickveenhof** [comment]
This time against the develop branch. Apologies! See #168 for reference and backscroll of this PR

**Comment by mikestowe** [comment]
Thanks!!!

**Comment by schmkr** [comment]
Hey guys. thanks for adding this feature. I was looking forward to this and just gave this version of raml2html a try.

Unfortunately, it didn't work for me, because our json schemas have an id with an http url, but that url is just a namespace and does not actually exist. 

We use other tools for validating our raml, schemas and examples with [ramlev](https://github.com/cybertk/ramlev) and that tool allow to supply a `fakeroot` for the schemas. Any change such a thing could also be added? Or at least an option to disable expanding `$ref` properties so we can still generate the html?

Thanks!

**Comment by schmkr** [comment]
By the way, the package ramlev is using for resolving the schemas is [refaker](https://github.com/json-schema-faker/refaker)

**Comment by nickveenhof** [comment]
Sure, please make a new issue + a corresponding pull request and we can look over it to see it doesn't break anything? I'd leave this one closed for now.

**Comment by schmkr** [comment]
Creating issue: done.

PR's might take a bit more time :)

**Pull request merged**
