### PR TITLE
Add --stdin param

### PR DESCRIPTION
**Pull request by Pentusha**
Hello.
It would be great if it is able to pass the contents of raml file through the stdin.
`raml2html --stdin < test.raml`

### CODE REVIEW

**Comment by kevinrenskers** [comment]
I like the idea, but not sure if I love the `--stdin` parameter. Is this really needed? Can't check for a combination of `process.stdin` and missing `program.args` so it just automatically works without this new parameter?

**Comment by Pentusha** [comment]
Entirely agree.
Now I have written a python program that just works like a charm without any workarounds with stdin.
```python
context = self.get_context_data(**kwargs)
response = self.render_to_response(context)
if 'raml' in request.GET:
    return response
proc = Popen([
    settings.RAML2HTML_BINARY,
    response.render().content,
], stdout=PIPE, stderr=PIPE)
stdout = proc.stdout.read().decode()
stderr = proc.stderr.read().decode()
return HttpResponse(stderr or stdout)
```
I don't know how its works (pass multi-line text param), but it works.
And commands ``raml2html example.raml > example.html`` and ``raml2html < example.raml > example.html`` looks pretty similar, but first one in shorter.
So I'm not sure thats really necessary feature.

**Comment by kevinrenskers** [comment]
I tried this with the example raml file in this repo.

`node bin/raml2html examples/example.raml` work
but `node bin/raml2html < examples/example.raml` doesn't. Same for `cat examples/example.raml | node bin/raml2html` for course.

Could you check out the error and make sure that this works for our example file?

**Comment by kevinrenskers** [comment]
And when I run it from the example folder itself (`node ../bin/raml2html < example.raml`) this is part of the output:

```
(node:6798) DeprecationWarning: fs.readSync's legacy String interfaceis deprecated. Use the Buffer API as mentioned in the documentation instead.
```

So that actually is part of the generated html file then.

**Comment by kevinrenskers** [comment]
Closing due to lack of updates. Please open a new PR if the mentioned issues are fixed, thanks!

**Pull request closed without merging**
