### PR TITLE
Add 'audience' param

### PR DESCRIPTION
**Pull request by ArtFlag**
**Improvement for ticket #377.**

Adds an `--audience` parameter that allows passing a value to the template. This allows conditional formatting of the output.

### CODE REVIEW

**Comment by kevinrenskers** [comment]
I'm sorry, but maybe it wasn't clear. The point is not to add specific support for this specific parameter.. ALL parameters are already passed into raml2html. So you don't need to add this `audience` parameter specifically. Also, the PR should be made to the develop branch :)

**Comment by ArtFlag** [comment]
Sorry for the branch mix up, I went to fast creating the second branch. I'll fix this if i have time to make it a generic name.

**Comment by kevinrenskers** [comment]
No the point is that you don't need any names :) It's all passed in as the `options` object already, just pass that to the process function, add it to ramlObj, boom done.

**Comment by kevinrenskers** [comment]
this is the idea: https://github.com/raml2html/raml2html/pull/380

**Comment by kevinrenskers** [comment]
Your last commit is indeed all it takes :) I just moved it to a different position but yeah this is all that's needed. I would definitely not include this `audience` param in the readme or CLI help.

**Comment by ArtFlag** [comment]
Maybe as a example/note though?

**Comment by kevinrenskers** [comment]
I've merged my version and relased 6.6.0. I don't think adding this specific thing to the examples and readme would've made sense. Other then that, nice PR, thanks :)

**Pull request closed without merging**
