### PR TITLE
Update resource.nunjucks

### PR DESCRIPTION
**Pull request by MichaelIT**
fixed for Example's `description` and `displayName` not rendered

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Thanks, but you're not checking for the existence of name and description, and since most examples I've seen so var are just a value, you'll end up with weird empty tags.

**Comment by MichaelIT** [comment]
tks for your suggestion, I already make a new commit for checking existence of name and description, and u need to review my another PR https://github.com/raml2html/raml2obj/pull/22

**Comment by sichvoge** [comment]
Can you add some screenshots and example RAMLs to that PR. Makes review a lot easier.

**Comment by kevinrenskers** [comment]
I've merged the raml2obj PR concerning this issue, so I'll review this PR before releasing a new version of raml2obj. Code looks good, but I want to check the visual style. Not too sure about those `<hr>` tags without seeing them first :)

**Comment by kevinrenskers** [comment]
BTW for future PR's, please choose the develop branch as the target, not master. Thanks!

**Comment by nickwb** [comment]
Just working through a few issues with this one.

image

**Comment by nickwb** [comment]
Hey @MichaelIT - Looks like we also need to update the examples sections in `item.nunjucks` to prevent this from breaking things.

**Comment by nickwb** [comment]
@MichaelIT - In the interest in fixing the breakages, I've branched from your PR over to here: https://github.com/raml2html/raml2html/pull/313

I'm going to close this for now, but you're more than welcome to continue contributing over on the new PR.

**Comment by MichaelIT** [comment]
ok, tks u work. @nickwb

**Pull request closed without merging**
