### PR TITLE
* Add nunjucks-includeData to be able to include JSON file as data in…

### PR DESCRIPTION
**Pull request by MrJamster**
… nunjucks file.

* Add addUniqueNr filter to get unique id's for each object/array panel.

Changes made related to PR Clickable objects and arrays #31 in raml2html/default-theme

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Can you explain the idea behind this PR? I am not really sure what it is for.

**Comment by mirjamat** [comment]
I included nunjucks-includeData so that one can run tests with JSON data without having to generate them from a RAML file, since I figured there might be something wrong with the raml2obj parsing. 

I discovered that the raml code 
`ScalarAnyOfArr: integer[] | string[]`
generates the JSON:
```
{"type":"array",
"items":{"anyOf":[{"type":"array","items":{"type":"integer"}},{"type":"string"}],
         "type":"union"},
"name":"ScalarAnyOfArr",
"displayName":"ScalarAnyOfArr",
"typePropertyKind":"TYPE_EXPRESSION",
"required":true,
"key":"ScalarAnyOfArr"}
```
and not:
```
{"anyOf":[{"type":"array","items":{"type":"integer"}},
          {"type":"array","items":{"type":"string"}}],
"type":"union",
"name":"ScalarAnyOfArr",
"displayName":"ScalarAnyOfArr",
"typePropertyKind":"TYPE_EXPRESSION",
"required":true,
"key":"ScalarAnyOfArr"}
```
which I had expected. 

The first JSON looks like something `MyArr` would generate when
`MyArr: MyUnion[]`
`MyUnion: integer[] | string`

So I used nunjucks-includeData to run tests with the second JSON.

The addUniqueNr filter is for generating unique id's to each expandable object/array panel. Since an object/array can appear more than once in the same window it is not safe to use only the object's or array's name as id.

**Comment by kevinrenskers** [comment]
You probably found a bug in raml2obj, but I don't think it makes a lot of sense to merge this stuff into raml2html. Sorry, closing this PR.

**Comment by MrJamster** [comment]
Sure, but the addUniqueNr filter is necessary in order for the PR Clickable objects and arrays #31 in raml2html/default-theme to work. Should I make a new PR for that?

**Comment by kevinrenskers** [comment]
I still have to dive into that PR, but yes that would be great, thanks.

**Pull request closed without merging**
