### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by chulkilee**
Currently develop and master are diverged, and I don't see good reasons to maintain separate develop branch.

This pull request is to merge develop into master and update the contributing section so that all development works can be toward master branch.

### CODE REVIEW

**Comment by chulkilee** [comment]
Ping @kevinrenskers - does it sound good to you?

**Comment by kevinrenskers** [comment]
It's setup so that master is whatever is released on npm, while ongoing development happens on develop. 

But I'm no longer involved with this project so it's up to the new maintainers if they want to change this setup.

**Comment by sichvoge** [comment]
I am also not seeing any reasons why we should allow any of the current development to always be on the master. I agree to @kevinrenskers that the version in master is the one that is published / in production vs really development and test. That's why I would say we keep it as it is.

Let's see what others say.

**Comment by sichvoge** [comment]
I think the question is when we do the next merge from develop into master and release something?

**Comment by chulkilee** [comment]
I saw some commits merged only to master, so I was confused. If you want to stick with develop branch, then fine. Just please merge master into develop to pick up them.

Here is my opinion: I was using develop branch in several private projects, and I found that in most cases I didn't need it since all release tasks depend on tags, not specific branch. If someone want to use released version, use npm or git tag, not just master branch. That's just my two cents.

**Pull request closed without merging**
