### PR TITLE
Improve multiple security schemes handling

### PR DESCRIPTION
**Pull request by DAICHl**
If there is more than one security scheme,
the generated html doesn't describe all of
them properly.

### CODE REVIEW

**Comment by DAICHl** [comment]
This came from https://github.com/raml2html/raml2html/pull/235 and the target branch has been changed from master to develop as you requested.

**Comment by kevinrenskers** [comment]
Thanks! Can you add an example file (or a bit to the existing example.raml file) that demonstrates this?

**Comment by DAICHl** [comment]
Hello, first of all, let me show what is improved(fixed) by this change.

If we have the following raml file which contains multiple security schemes,
```
#%RAML 0.8
title: Sample
version: v1
protocols:
  - HTTPS

baseUri: https://www.example.com

securedBy: [OAuth2.0, x-something]
securitySchemes:
  - OAuth2.0:
      description: OAuth2.0 for authenticating all API requests.
      type: OAuth 2.0
      describedBy:
          headers:
              Authorization:
                  description: |
                    For sending a valid OAuth 2 token.
                  type: string
                  required: true
      settings:
        authorizationUri: https://auth.example.com/2.0
        accessTokenUri: https://auth.example.com/2.0
        authorizationGrants: [ code, token ]
  - x-something:
      description: |
        The proprietary x-something header.
      type: x-something
      describedBy:
          headers:
              X-SOMETHING:
                  description: |
                    For sending a valid token.
                  type: string
                  required: false

/foo:
  /bar:
    get:
      description:
        something...
```

the generated html shows:

[Without this change]
screen shot 2016-08-04 at 22 32 38

[With this change]
screen shot 2016-08-04 at 22 31 39

As you can see, the 2 security schemes properly appear. Please let me know if you need more info!

**Comment by kevinrenskers** [comment]
Yep, awesome stuff. Can you just add this example either as a new RAML file or as a piece in the existing example.raml, so that we have example / test files to test future versions of raml2html against?

**Comment by DAICHl** [comment]
I have just added one more commit. How about this?

**Comment by kevinrenskers** [comment]
Great, thanks! 👍

**Pull request merged**
